### PR TITLE
Fix issues sort by status then timestamp

### LINKED ISSUE #89: Issues are not sorted by pending then timestamp

### PR DESCRIPTION
**Pull request by stein414**
## What this does
Fixes #89 by sorting it by status (pending then closed) followed by timestamp

## How to test
1. Run SunRez and check that the existing data for issues (if any) is sorted pending then closed
  - If same status then sort by timestamp
2. add issues with timestamp between min existing timestamp and max existing timestamp
3. add issues with current time as timestamp (by not specifying timestamp parameter)
4. add issues with timestamp earlier than any other issues
3. edit an issue to test same equivalence partitions like step 2 - 4

### CODE REVIEW

File: src/main/java/seedu/address/model/issue/Issue.java [hunk 1]
```diff
@@ -131,7 +131,11 @@ public String toString() {
 
     @Override
     public int compareTo(Issue other) {
-        return timestamp.compareTo(other.timestamp);
```
Comment (DrWala) [inline src/main/java/seedu/address/model/issue/Issue.java:134]: I think it would be better to change this form to use the standard if-else syntax. There are 3 reasons for suggesting this:

1. It improves readability of what the function is doing.
2. The code-base throughout does not use ternary operators in the `compareTo` or `equals` function. They typically write it out in full form.
3. The module's coding standards require if-else type statements to take a certain form: https://se-education.org/guides/conventions/java/intermediate.html#layout

Thus, I would recommend changing it.

**Review by DrWala — CHANGES_REQUESTED** [review]

**Review by DrWala — APPROVED** [review]
LGTM
