### PR TITLE
Fix(Sort): Sort residents by alphabetical order

### LINKED ISSUE #203: [PE-D] rlist not sorting residents alphabetically
As detailed in the UG:

However, after adding a new resident to sample data with 
radd n/AAAA p/9999 e/abs@123.com y/1, we have the following, with AAAA in position 7.

After calling rlist, no change occurs even though AAAA is lexicographically smaller than Alex Yeoh.

Same issue if another person, Aamar is added and rlist is called.
radd n/Aamar p/9999 e/abc@123.com y/1

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: nickyfoo/ped#5

### LINKED ISSUE #232: [PE-D] rlist not sorting
rlist not showing residents in alphbetical order

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: BenedictBCJJ/ped#6

### PR DESCRIPTION
**Pull request by colintkn**
### What this does
Closes #203 
Closes #232 

### How to test
`clear`
`radd n/Zender Doe p/98765432 e/johnd@example.com y/1`
`radd n/John Doe p/98765432 e/johnd@example.com y/1`
`radd n/Aaron Doe p/98765432 e/johnd@example.com y/1`
`radd n/Charles Doe p/98765432 e/johnd@example.com y/1`

The residents listed should be sorted alphabetically.

### CODE REVIEW

File: src/main/java/seedu/address/model/resident/UniqueResidentList.java [hunk 1]
```diff
@@ -86,11 +88,13 @@ public void remove(Resident toRemove) {
         if (!internalList.remove(toRemove)) {
             throw new ResidentNotFoundException();
         }
+        FXCollections.sort(internalList);
```
Comment (stein414) [inline src/main/java/seedu/address/model/resident/UniqueResidentList.java:91]: Removing probably no need to sort again but I think it is ok to have it here too since it probably does not affect performance much at this scale

**Review by stein414 — APPROVED** [review]
LGTM. Briefly tested and it seems to be showing in alphabetical order
